config/routes.rb
Rails.application.routes.draw do

  get 'imagenes/frontal'
  get 'imagenes/perfil'
  resources :pacientes, shallow: true do
    resources :mediciones
  end

  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  get 'estatico/perfil'
  get 'estatico/resultados'
  get 'estatico/grafica'
  get 'estatico/tulogopeda'

  root to: "estatico#inicio"

end

app/controllers/estatico_controller.rb
class EstaticoController < ApplicationController
  before_action :authenticate_user!, only: [:perfil, :resultados, :grafica]
  def inicio
  end

  def perfil
    @paciente = Paciente.find(params[:paciente_id])
  end

  def resultados
    @medicione = Medicione.find(params[:medicione_id])
    @paciente = @medicione.paciente

    @ojo_comisura_derecho = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'ojo_comisura_derecho'
    ).first
    @ojo_comisura_izquierdo = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'ojo_comisura_izquierdo'
    ).first
    @altura_labio_superior = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'altura_labio_superior'
    ).first
    @altura_labio_inferior = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'altura_labio_inferior'
    ).first

    @cupido_derecho = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'cupido_derecho'
    ).first

    @cupido_izquierdo = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'cupido_izquierdo'
    ).first

    @leporino = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'leporino'
    ).first

    @trichion_menton = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'trichion_menton'
    ).first

    @distancia_intercisiva_maxima = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'distancia_intercisiva_maxima'
    ).first

    @tercio_superior = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'tercio_superior'
    ).first

    @tercio_medio = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'tercio_medio'
    ).first

    @tercio_inferior = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'tercio_inferior'
    ).first

    @tercio_inferior_superior = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'tercio_inferior_superior'
    ).first

    @tercio_inferior_medio = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'tercio_inferior_medio'
    ).first

    @tercio_inferior_inferior = Medida.where(
      sexo: @paciente.sexo,
      edad: Time.now.year-@paciente.fecha_nacimiento.year,
      zona: 'tercio_inferior_inferior'
    ).first

  end

  def grafica
    @medicion = Medicione.find(params[:medicione_id])
    @mediciones = Medicione.where(paciente_id: @medicion.paciente_id)
  end

  def tulogopeda
    @usuarios = User.all
  end
end

app/helpers/estatico_helper.rb
module EstaticoHelper
  def porcentaje numerador, array
    unless numerador.nil? or array.nil?
      numerador / array.max
    else
      "No hay medidas suficientes para este calculo"
    end

  end

  def debora medicion, medida
    if medida.present? and medicion.present?
      if medicion.between?(medida.inferior,medida.superior)
        '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>'.html_safe
      else
        '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>'.html_safe
      end
    end

  end

end

app/views/estatico/_preguntas_frecuentes.html.erb
<div class="preguntasFrecuentes">
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		<div class="" role="" id="">
			<h4 class="panel-title">
				<a role="" data-toggle="collapse" data-parent="#accordion" href='<%= "#collapse-"+numero %>'  aria-expanded="true" aria-controls='<%= "collapse-"+numero %>'>
          <h4 class="leerMas"><%= pregunta %></h4>
				</a>
			</h4>
		</div>
		<div id='<%= "collapse-"+numero %>' class="panel-collapse collapse" role="tabpanel" aria-labelledby='<%= "heading-"+numero %>'>
			<div class="panel-body PostContenido">
				<div>
          <p><%= respuesta %></p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/estatico/grafica.html.erb
<article id="grafica" class="container-fluid cuerpo">

  <section class="titulo" class="row">
     <div class="col-xs-12 text-center sub-titulo">
       <h2 class="titulosMovil"> 5 <span class="rojo">/</span> GRÁFICA DE SEGUIMIENTO</h2>
     </div>
  </section>

  <section class="row paddingtop">
    <div class="col-xs-12 text-center paddingtop">
      <h2 class="">Zona en construcción</h2>
    </div>
    <div class="ct-chart col-md-12">
    </div>
    <div class="col-xs-12 text-center paddingtop">
      <h4>COMISURA LABIAL / BORDE EXTERIOR DEL OJO:</h4>
    </div>
    <div class="col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 grafica">
      <%= image_tag 'grafica.png', alt: 'grafica', height: '', width: '100%' %>
    </div>

    <div class="col-xs-12 text-center paddingtop">
      <h4>COMISURA LABIAL / INCISURAINTERTRÁGICA:</h4>
    </div>
    <div class="col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 grafica">
      <%= image_tag 'grafica.png', alt: 'grafica', height: '', width: '100%' %>
    </div>

    <div class="col-xs-12 text-center paddingtop">
      <h4>LÍNEA CIERRE LABIAL / BORDES DE ARCOS CÚPIDO:</h4>
    </div>
    <div class="col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 grafica">
      <%= image_tag 'grafica.png', alt: 'grafica', height: '', width: '100%' %>
    </div>

    <div class="col-xs-12 text-center paddingtop">
      <h4>GONIO / MENTÓN:</h4>
    </div>
    <div class="col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 grafica">
      <%= image_tag 'grafica.png', alt: 'grafica', height: '', width: '100%' %>
    </div>

    <div class="col-xs-12 text-center paddingtop">
      <h4>TERCIOS:</h4>
    </div>
    <div class="col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 grafica">
      <%= image_tag 'grafica.png', alt: 'grafica', height: '', width: '100%' %>
    </div>

    <div class="col-xs-12 text-center paddingtop">
      <h4>TERCIOS DEL 1/3 INFERIOR:</h4>
    </div>
    <div class="col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10 grafica">
      <%= image_tag 'grafica.png', alt: 'grafica', height: '', width: '100%' %>
    </div>

  </section>


  <section class="navegacion row paddingtop text-center">
    <div class="col-sm-offset-1 col-sm-5 col-xs-offset-2 col-xs-4">
      <span onclick="goBack()" class="glyphicon glyphicon-circle-arrow-left btn-pasos"></span>
    </div>
    <div class="col-sm-5 col-xs-4">
      <span class="glyphicon glyphicon-ok-sign btn-pasos ruta" data-url="/"></span>
    </div>
  </section>
</article>

app/views/estatico/inicio.html.erb
<article class="container-fluid cuerpo">

    <section id="titulo" class="row">
        <div class="col-xs-offset-2 col-xs-8"><br>
            <%= image_tag 'login/login.png', alt: 'login', heigh: '', width: '100%', class: 'logologin' %>
        </div>
        <div class="col-xs-offset-2 col-xs-8 paddingtop">
            <%= image_tag 'login/malla.png', alt: 'login', heigh: '', width: '100%', class: 'logologin' %>
        </div>
    </section>
    <section  id="login" class="row">
        <div class="col-sm-offset-4 col-sm-4 col-xs-12 paddingtop paddingbottom">
            <%= form_for(:user, url: session_path(:user)) do |f| %>
                <div class="row text-center">
                    <div class="form-group col-sm-6">
                        <%= f.label :email, "Correo electrónico" %>
                        <%= f.email_field :email, autofocus: true %>
                    </div>

                    <div class="form-group col-sm-6">
                        <%= f.label :password, "Contraseña" %>
                        <%= f.password_field :password, autocomplete: "off" %>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group checkbox text-center">
                        <%= f.check_box :remember_me %>
                        <%= f.label :remember_me, "Recordarme" %>
                    </div>
                </div>
                <div class="text-center">
                    <%= f.submit "Entra" %><br>
                    <%= link_to "¿Olvidaste tu contraseña?", new_password_path(:user) %>
                </div>
            <% end %>
        </div>
    </section>
    <section id="parte1" class="row">
      <div class="col-xs-12">
        <span class="titulosLogin">VALOR AÑADIDO</span>
        <div><br>En esta era digital, colocar la tecnología al servicio profesional se convierte en algo natural. La operatividad que proporciona en entornos laborales consigue que con la misma dedicación de tiempo, simplifiquemos el empleo de recursos y obtengamos resultados más productivos.
        </div>
     </div>
    </section>
    <section id="parte2" class="row">
      <div class="col-xs-12">
        <span class="titulosLogin">VISIÓN 2.0</span>
        <div><br>En nuestra visión 2.0 elaboramos una propuesta que unifica distintos protocolos de actuación, para obtener del uso de la Logometría Orofacial un registro integral de las características de nuestros pacientes.
        </div>
        <%= image_tag 'login/20.png', alt: '', heigh: '', width: '80%', class: 'imagelogin' %>
     </div>
    </section>
    <section id="parte3" class="row">
      <div class="col-xs-12">
        <span class="titulosLogin2">PRIVACIDAD DE DATOS</span>
        <div><br>Logometría Orofacial ha adoptado en su sistema de información las medidas técnicas y organizativas legalmente requeridas, a fin de garantizar la seguridad y confidencialidad de los datos almacenados, evitando así, en la medida de lo posible, su alteración, pérdida, tratamiento o acceso no autorizado.
        </div>
        <div><br>
          <%= image_tag 'login/candado.png', alt: '', heigh: '', width: '8%', style: 'margin:auto; opacity:0.2;' %>
          <%= image_tag 'login/candado.png', alt: '', heigh: '', width: '8%', style: 'margin:auto; opacity:0.4;' %>
          <%= image_tag 'login/candado.png', alt: '', heigh: '', width: '8%', style: 'margin:auto; opacity:0.6;' %>
          <%= image_tag 'login/candado.png', alt: '', heigh: '', width: '8%', style: 'margin:auto; opacity:0.8;' %>
          <%= image_tag 'login/candado.png', alt: '', heigh: '', width: '8%', style: 'margin:auto; opacity:1;' %>
        </div>
     </div>
    </section>
    <section id="parte4" class="row">
      <div class="col-xs-12">
        <span class="titulosLogin">¿POR QUÉ NOSOTROS?</span>
        <div><br>Porque la Logometría Orofacial nos permite reducir los tiempos de trabajo, porque facilita la comunicación entre profesionales, porque acerca al paciente y al logopeda, porque aporta objetividad al tratamiento de los datos...y la pregunta es ¿ por qué no?
        </div><br>
        <div class="col-sm-12 padding-sup-inf">
          <div id="carrusel-nosotros" class="carousel slide" data-ride="carousel" data-pause="false" data-interval="2500">
          <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <img src="img/carrousel/01.png" alt="" width="100%" style="margin:auto;">
                <%= image_tag 'carrousel/01.png', alt: '', width: '100%', style: 'margin:auto;' %>
                <div class="carousel-caption">
                  <h3 class="negro"></h3>
                  <p></p>
                </div>
              </div>
              <div class="item">
                <%= image_tag 'carrousel/02.png', alt: '', width: '100%', style: 'margin:auto;' %>
                <div class="carousel-caption">
                  <h3></h3>
                  <p></p>
                </div>
            </div>
            <div class="item">
                <%= image_tag 'carrousel/03.png', alt: '', width: '100%', style: 'margin:auto;' %>
              <div class="carousel-caption">
                <h3></h3>
                <p></p>
              </div>
            </div>
          </div>
        </div>
     </div>
    </section>
    <section id="parte5" class="row">
      <div class="col-xs-12">
        <span class="titulosLogin">CONTACTO</span>
        <div><br>Déjanos un mensaje junto a tu nombre y email y te responderemos con la mayor brevedad.<br><br>
          Coméntanos su caso, sus dudas o sugerencias. Estaremos encantados de poder ofrecerle ayuda y orientación personalizada.
        </div>
      </div>
      <div id="contactoDatos" class="row cuerpoVistas">
        <div class="col-sm-offset-2 col-sm-8">
          <div id="formulario_contacto" class="container-fluid">
            <form action="result.php" method="post">
              <span class="blanco">Nombre*</span><br>
                <input class="barra_formulario" name="name" skinpart="name" type="text" placeholder="Tu nombre" maxlenght="50" /><br>
              <span class="blanco">Email*</span><br>
                <input class="barra_formulario" name="email" skinpart="email" type="text" placeholder="Tu email" maxlenght="50" /><br>
              <span class="blanco">Asunto*</span><br>
                <input class="barra_formulario" name="subject" skinpart="subject" type="text" placeholder="Escribe el asunto" maxlenght="50" /><br>
              <span class="blanco">Tu comentario*</span><br>
                <textarea class="barra_formulario_mensaje" name="message" skinpart="message" placeholder="Escribe tu comentario"></textarea><br>
              <span class="blanco">Su dirección de correo electrónico no será publicada. Todos los campos son obligatorios.<br><br></span><input class="btn enviar_correo" name="send" skinpart="send" type="submit" value="ENVIAR" />
            </form>
          </div>
        </div>
      </div>
    </section>
</article>

app/views/estatico/perfil.html.erb
<article class="container-fluid cuerpo">
	<section class="titulo" class="row">
      <div class="col-xs-12 text-center sub-titulo">
        <h2 class="titulosMovil"> 2 <span class="rojo">/</span> SELECCIÓN PERFIL</h2>
      </div>
    </section>

    <section class="row paddingtop">
    	<div class="col-xs-12 text-center paddingtop">
    		<h4>ESCOGER SOLO UN PERFIL</h4>
    	</div>
    </section>

    <section class="row paddingtop">
    	<div class="col-sm-offset-3 col-sm-2 col-xs-12 text-center contenedor-icono-seleccion"></br>
        <%= image_tag 'paso02/frontal.png',
            alt: 'frontal',
            height: '',
            width: '100%',
            class: "perfiles"  %></br>
    		<span class="icono-seleccion">FRONTAL</span>
    	</div>
    	<div class="col-sm-2 col-xs-12 text-center contenedor-icono-seleccion"></br>
        <%= image_tag 'paso02/lateral.png',
            alt: 'frontal',
            height: '',
            width: '100%',
            class: "perfiles"  %></br>
    		<span class="icono-seleccion">LATERAL</span>
    	</div>
    	<div class="col-sm-2 col-xs-12 text-center contenedor-icono-seleccion"></br>
        <%= image_tag 'paso02/busto.png',
            alt: 'frontal',
            height: '',
            width: '100%',
            class: "perfiles"  %></br>
    		<span class="icono-seleccion">BUSTO</span>
    	</div>

      <div class="form-group">
        <label class="control-label col-xs-12 text-center">SEGUIMIENTO:</label>
        <div class="col-sm-offset-3 col-sm-3 text-center">
          <label class="radio-inline">
            <input type="radio" name="genderRadios" value=""> ESTÉTICA
          </label>
        </div>
        <div class="col-sm-3 text-center">
          <label class="radio-inline">
            <input type="radio" name="genderRadios" value=""> FUNCIONAL
          </label>
        </div>
      </div>

    </section>

    <section class="navegacion row paddingtop text-center">
      <div class="col-sm-offset-1 col-sm-5 col-xs-offset-2 col-xs-4">
        <span onclick="goBack()" class="glyphicon glyphicon-circle-arrow-left btn-pasos"></span>
      </div>
      <div class="col-sm-5 col-xs-4">
        <span class="glyphicon glyphicon-circle-arrow-right btn-pasos ruta" data-url="<%= url_for new_paciente_medicione_path(params[:paciente_id])%>"></span>
      </div>
    </section>
</article>

app/views/estatico/resultados.html.erb
<article id="resultados" class="container-fluid cuerpo">
	<section class="titulo" class="row">
      <div class="col-xs-12 text-center sub-titulo">
        <h2 class="titulosMovil"> 3 <span class="rojo">/</span> RESULTADOS</h2>
      </div>
    </section>

    <section class="row paddingtop">

        <div class="col-xs-12 text-center paddingtop">
            <h4>MEDIA ARITMÉTRICA</h4>
        </div>

    	<div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
            <div class="col-sm-4 col-xs-12 musculo">
                COMISURA LABIAL / BORDE EXTERIOR DEL OJO:
            </div>
            <div class="col-sm-4 col-xs-6 text-center">
              <span>Derecho: </span><span><%= @medicione.ojo_comisura_derecho %></span>
              <%= debora @medicione.ojo_comisura_derecho,@ojo_comisura_derecho %>
            </div>
            <div class="col-sm-4 col-xs-6 text-center">
              <span>Izquierdo: </span><span><%= @medicione.ojo_comisura_izquierdo %></span>
              <%= debora @medicione.ojo_comisura_izquierdo,@ojo_comisura_izquierdo %>
            </div>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
            <div class="col-sm-4 col-xs-12 musculo">
                ALTURA DEL LABIO SUPERIOR:
            </div>
            <div class="col-sm-8 col-xs-6 text-center">
              <span><%= @medicione.altura_labio_superior %></span>
              <%= debora @medicione.altura_labio_superior,@altura_labio_superior %>
            </div>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
            <div class="col-sm-4 col-xs-12 musculo">
                ALTURA DEL LABIO INFERIOR:
            </div>
            <div class="col-sm-8 col-xs-6 text-center">
              <span><%= @medicione.altura_labio_inferior %></span>
              <%= debora @medicione.altura_labio_inferior,@altura_labio_inferior %>
            </div>
        </div>


        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
            <div class="col-sm-4 col-xs-12 musculo">
                FILTRO:
            </div>
            <div class="col-sm-8 col-xs-12 text-center">
              <span><%= @medicione.leporino %></span>
              <%= debora @medicione.leporino,@leporino %>
            </div>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
            <div class="col-sm-4 col-xs-12 musculo">
                TRICHION / GNATIO:
            </div>
            <div class="col-sm-8 col-xs-12 text-center">
              <span><%= @medicione.trichion_menton %></span>
              <%= debora @medicione.trichion_menton,@trichion_menton %>
            </div>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
          <div class="col-sm-4 col-xs-12 musculo">
            DISTANCIA INTERCISIVA MAXIMA
          </div>
          <div class="col-sm-8 col-xs-12 text-center">
               <span><%= @medicione.distancia_intercisiva_maxima %></span>
               <%= debora @medicione.distancia_intercisiva_maxima,@distancia_intercisiva_maxima %>
          </div>
        </div>
        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados text-center">
            <div class="col-sm-12 musculo">
                <span>TERCIOS</span>
            </div>
            <div class="col-sm-4 col-xs-12">
                TRICHION / GLABELA: <BR>
                <span><%= @medicione.tercio_superior %></span>
                <%= debora @medicione.tercio_superior,@tercio_superior %>
            </div>
            <div class="col-sm-4 col-xs-12">
                GLABELA / SUBNASAL: <BR>
                <span><%= @medicione.tercio_medio %></span>
                <%= debora @medicione.tercio_medio,@tercio_medio %>
            </div>
            <div class="col-sm-4 col-xs-12">
                 SUBNASAL / GNATIO: <BR>
                 <span><%= @medicione.tercio_inferior %></span>
                 <%= debora @medicione.tercio_inferior,@tercio_inferior %>
            </div>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados text-center">
            <div class="col-sm-12 musculo">
                <span>TERCIOS del 1/3 INFERIOR</span>
            </div>
            <div class="col-sm-4 col-xs-12">
                SUBNASAL / ESTOMIO: <BR>
                <span><%= @medicione.tercio_inferior_superior %></span>
                <%= debora @medicione.tercio_inferior_superior,@tercio_inferior_superior %>
            </div>
            <div class="col-sm-4 col-xs-12">
                ESTOMIO / SUPRAMENTONIANO: <BR>
                <span><%= @medicione.tercio_inferior_medio %></span>
                <%= debora @medicione.tercio_inferior_medio,@tercio_inferior_medio %>
            </div>
            <div class="col-sm-4 col-xs-12">
                 SUPRAMENTONIANO / GNATIO: <BR>
                 <span><%= @medicione.tercio_inferior_inferior %></span>
                 <%= debora @medicione.tercio_inferior_inferior,@tercio_inferior_inferior %>
            </div>
        </div>

    </section>

    <section class="row paddingtop">
        <div class="col-xs-12 text-center">
            <h4>COMPARATIVA EN  %</h4>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados sologrande">
            <div class="col-sm-4 col-xs-12">
            </div>
            <div class="col-sm-4 col-xs-6 text-center">
                DERECHO
            </div>
            <div class="col-sm-4 col-xs-6 text-center">
                IZQUIERDO
            </div>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados">
            <div class="col-sm-4 col-xs-12 text-center musculo">
                COMISURA LABIAL / BORDE EXTERIOR DEL OJO:
            </div>
            <div class="col-sm-4 col-xs-6 text-center">
                <span class="solopequeno">DCHO</span><br>
                <span>
                  <%= porcentaje(@medicione.ojo_comisura_derecho, [
                    @medicione.ojo_comisura_derecho,
                    @medicione.ojo_comisura_izquierdo]) %>
                </span>
            </div>
            <div class="col-sm-4 col-xs-6 text-center">
                <span class="solopequeno">IZQ</span><br>
                <span>
                  <%= porcentaje(@medicione.ojo_comisura_izquierdo, [
                    @medicione.ojo_comisura_derecho,
                    @medicione.ojo_comisura_izquierdo]) %>
                </span>
            </div>
        </div>

    </section>

    <section class="row paddingtop">
        <div class="col-xs-12 text-center">
            <h4>COMPARATIVA DE LOS TERCIOS</h4>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados text-center">
            <div class="col-sm-4 col-xs-12">
                <span class="musculo">SUPERIOR</span><BR>
                  <span>
                    <%= porcentaje(@medicione.tercio_superior, [
                      @medicione.tercio_superior,
                      @medicione.tercio_medio,
                      @medicione.tercio_inferior]) %>
                  </span>
            </div>
            <div class="col-sm-4 col-xs-12">
                <span class="musculo">MEDIO</span><BR>
                  <span>
                    <%= porcentaje(@medicione.tercio_medio, [
                      @medicione.tercio_superior,
                      @medicione.tercio_medio,
                      @medicione.tercio_inferior]) %>
                  </span>
            </div>
            <div class="col-sm-4 col-xs-12">
                <span class="musculo">INFERIOR</span><BR>
                  <span>
                    <%= porcentaje(@medicione.tercio_inferior, [
                      @medicione.tercio_superior,
                      @medicione.tercio_medio,
                      @medicione.tercio_inferior]) %>
                  </span>
            </div>
        </div>

    </section>

    <section class="row paddingtop">
        <div class="col-xs-12 text-center">
            <h4>TERCIOS DEL 1/3 INFERIOR</h4>
        </div>

        <div class="col-sm-offset-2 col-sm-8 col-xs-12 cuadros-resultados text-center">
            <div class="col-sm-4 col-xs-12">
                <span class="musculo">SUPERIOR</span><BR>
                  <span>
                    <%= porcentaje(@medicione.tercio_inferior_superior, [
                      @medicione.tercio_inferior_superior,
                      @medicione.tercio_inferior_medio,
                      @medicione.tercio_inferior_inferior]) %>
                  </span>
            </div>
            <div class="col-sm-4 col-xs-12">
                <span class="musculo">MEDIO</span><BR>
                  <span>
                    <%= porcentaje(@medicione.tercio_inferior_medio, [
                      @medicione.tercio_inferior_superior,
                      @medicione.tercio_inferior_medio,
                      @medicione.tercio_inferior_inferior]) %>
                  </span>
            </div>
            <div class="col-sm-4 col-xs-12">
                <span class="musculo">INFERIOR</span><BR>
                  <span>
                    <%= porcentaje(@medicione.tercio_inferior_inferior, [
                      @medicione.tercio_inferior_superior,
                      @medicione.tercio_inferior_medio,
                      @medicione.tercio_inferior_inferior]) %>
                  </span>
            </div>
        </div>

    </section>

    <section class="navegacion row paddingtop text-center">
      <div class="col-sm-offset-1 col-sm-5 col-xs-offset-2 col-xs-4">
        <span class="glyphicon glyphicon-circle-arrow-left btn-pasos go-back">
        </span>
      </div>
      <div class="col-sm-5 col-xs-4">
        <span class="glyphicon glyphicon-circle-arrow-right btn-pasos ruta" data-url="<%= url_for paciente_path(@medicione.paciente.id) %>">
        </span>
      </div>

    </section>
</article>