config/routes.rb
Rails.application.routes.draw do

  get 'imagenes/frontal'
  get 'imagenes/perfil'
  resources :pacientes, shallow: true do
    resources :mediciones
  end

  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  get 'estatico/perfil'
  get 'estatico/resultados'
  get 'estatico/grafica'
  get 'estatico/tulogopeda'

  root to: "estatico#inicio"

end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  has_many :medicione, dependent: :destroy
  belongs_to :user
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    #@pacientes = Paciente.all
    @pacientes = current_user.pacientes
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    #@paciente = Paciente.new(paciente_params)
    @paciente = current_user.pacientes.build(paciente_params)
    respond_to do |format|
      if @paciente.save
        format.html { redirect_to new_paciente_medicione_path(paciente_id: @paciente.id), notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente creado con exito.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nombre, :apellidos, :telefono, :fecha_nacimiento, :motivo_consulta, :anamnesis, :sexo, :fecha_inicio_terapia)
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<article id="datos-paciente" class="container-fluid cuerpo">
    <section class="titulo" class="row">
      <div class="col-xs-12 text-center sub-titulo">
        <h2 class="titulosMovil"> 1 <span class="rojo">/</span> DATOS PERSONALES PACIENTES</h2>
      </div>
    </section><br>

    <section id="login" class="row">
      <div class="col-sm-offset-2 col-sm-8 col-xs-12">
        <%= form_for(@paciente) do |f| %>
          <% if @paciente.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>
              <ul>
              <% @paciente.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group paddingtop paddingbottom">
            <%= f.label :nombre, class: 'control-label col-xs-12' %>
            <div class="col-xs-12">
              <%= f.text_field :nombre, class: 'form-control', placeholder: 'Nombre' %>
            </div>
          </div>

          <div class="form-group paddingtop paddingbottom">
            <%= f.label :apellidos, class: 'control-label col-xs-12' %>
            <div class="col-xs-12">
              <%= f.text_field :apellidos, class: 'form-control', placeholder: 'Apellidos' %>
            </div>
          </div>

          <div class="form-group paddingtop paddingbottom">
            <%= f.label :telefono, class: 'control-label col-xs-12' %>
            <div class="col-xs-12">
              <%= f.text_field :telefono, class: 'form-control', placeholder: 'Teléfono de contacto' %>
            </div>
          </div>

          <div class="col-xs-12">
            <%= f.label :fecha_nacimiento, class: 'control-label' %>
            <br>
            <%= f.date_select :fecha_nacimiento,
                {start_year: Time.now.year-80,
                end_year: Time.now.year,
                order: [:day, :month, :year]},
                class: "col-md-4" %>
          </div>

          <div class="form-group paddingtop paddingbottom">
            <%= f.label :motivo_consulta, class: 'control-label col-xs-12' %>
            <div class="col-xs-12">
              <%= f.text_field :motivo_consulta, class: 'form-control', placeholder: 'Motivo de la consulta' %>
            </div>
          </div>

          <div class="form-group paddingtop paddingbottom">
            <%= f.label :anamnesis, class: 'control-label col-xs-12' %>
            <div class="col-xs-12">
              <%= f.text_field :anamnesis, class: 'form-control', placeholder: 'Anamnesis' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :sexo, class: 'control-label col-xs-12'%><br>
            <div class="col-xs-6 text-center">
              Hombre</br>
              <%= f.radio_button :sexo, "Hombre" %>
            </div>
            <div class="col-xs-6 text-center">
              Mujer</br>
              <%= f.radio_button :sexo, "Mujer" %>
            </div>
          </div>

          <div class="col-xs-12">
            <%= f.label :fecha_inicio_terapia %><br>
            <%= f.date_select :fecha_inicio_terapia,
                {start_year: Time.now.year-10,
                end_year: Time.now.year,
                order: [:day, :month, :year]},
                class: "col-md-4" %>
          </div>
        <% end %>
      </div>
    </section>

  <section class="navegacion row paddingtop text-center">
    <div class="col-sm-offset-1 col-sm-5 col-xs-offset-2 col-xs-4">
      <span class="glyphicon glyphicon-circle-arrow-left btn-pasos go-back"></span>
    </div>
    <div class="col-sm-5 col-xs-4">
      <span class="glyphicon glyphicon-circle-arrow-right btn-pasos new-paciente"></span>
    </div>
  </section>
</article>

app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form' %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>
<article class="container-fluid cuerpo">

  <div class="row">
    <div class="col-md-6">
      <h1>Nombre del paciente</h1>
    </div>
    <div class="col-md-6">
      <%= link_to 'Nuevo paciente', new_paciente_path, class: 'btn btn-default' %>
    </div>
  </div>
  <h2>Pacientes</h2>
  <div class="row">
    <% @pacientes.each do |paciente| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="row">
          <div class="col-md-3">
            <div class="panel-thumbnail"><%= image_tag 'portrait.png', class: 'img-responsive' %></div></div>
          <div class="col-md-9">
            <div class="panel-body">
              <p class="lead"><%= paciente.nombre %></p>
              <div class="col-md-6">
                <p><%= paciente.fecha_nacimiento %></p>
              </div>
              <div class="col-md-6">
                <p><%= paciente.sexo %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= link_to 'Ver paciente', paciente_path(paciente), class: 'btn btn-default' %>
          </div>
          <div class="col-md-6">
            <%= link_to 'Nueva medicion', new_paciente_medicione_path(paciente), class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</article>

app/views/pacientes/new.html.erb
<%= render 'form' %>

app/views/pacientes/show.html.erb
<section id="mostrar-paciente">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag 'portrait.png', class: 'img-responsive' %>
    </div>
    <div class="col-md-3">
      <h3>Nombre: <%= @paciente.nombre %></h3>
      <h4>Fecha de nacimiento: <%= @paciente.fecha_nacimiento %></h4>
      <h4>Sexo: <%= @paciente.sexo %></h4>
    </div>
    <div class="col-md-6">
      <h4>Fecha de inicio de la terapia: <%= @paciente.fecha_inicio_terapia %></h4>
      <h4>Motivo de la consulta:</h4>
      <p><%= @paciente.motivo_consulta %></p>
      <h4>Anamnesis:</h4>
      <p><%= @paciente.anamnesis %></p>
    </div>
  </div>

  <div class="row">
    <div class="ct-chart"></div>
    <div class="col-md-6">
      <%= link_to 'Listado de pacientes', pacientes_path, class: 'btn btn-default'  %>
    </div>
    <div class="col-md-6">
      <%= link_to 'Nueva medicion', new_paciente_medicione_path(@paciente), class: 'btn btn-default' %>
    </div>

  </div>
</div>