config/routes.rb
Rails.application.routes.draw do

  get 'imagenes/frontal'
  get 'imagenes/perfil'
  resources :pacientes, shallow: true do
    resources :mediciones
  end

  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  get 'estatico/perfil'
  get 'estatico/resultados'
  get 'estatico/grafica'
  get 'estatico/tulogopeda'

  root to: "estatico#inicio"

end

app/models/medicione.rb
class Medicione < ActiveRecord::Base
  belongs_to :paciente
end

app/controllers/mediciones_controller.rb
class MedicionesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_medicione, only: [:show, :edit, :update, :destroy]

  # GET /mediciones
  # GET /mediciones.json
  def index
    @mediciones = Medicione.all
  end

  # GET /mediciones/1
  # GET /mediciones/1.json
  def show
  end

  # GET /mediciones/new
  def new
    @medicione = Medicione.new
    @paciente = Paciente.find(params[:paciente_id])
  end

  # GET /mediciones/1/edit
  def edit
  end

  # POST /mediciones
  # POST /mediciones.json
  def create
    @medicione = Medicione.new(medicione_params)

    respond_to do |format|
      if @medicione.save
        format.html { redirect_to estatico_resultados_path(medicione_id: @medicione.id), notice: 'Medicione was successfully created.' }
        format.json { render :show, status: :created, location: @medicione }
      else
        format.html { render :new }
        format.json { render json: @medicione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mediciones/1
  # PATCH/PUT /mediciones/1.json
  def update
    respond_to do |format|
      if @medicione.update(medicione_params)
        format.html { redirect_to @medicione, notice: 'Medicione was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicione }
      else
        format.html { render :edit }
        format.json { render json: @medicione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mediciones/1
  # DELETE /mediciones/1.json
  def destroy
    @medicione.destroy
    respond_to do |format|
      format.html { redirect_to mediciones_url, notice: 'Medicione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicione
      @medicione = Medicione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicione_params
      params.require(:medicione).permit(
        :ojo_comisura_derecho,
        :ojo_comisura_izquierdo,
        :altura_labio_superior,
        :altura_labio_inferior,
        :leporino,
        :trichion_menton,
        :tercio_superior,
        :tercio_medio,
        :tercio_inferior,
        :tercio_inferior_superior,
        :tercio_inferior_medio,
        :tercio_inferior_inferior,
        :paciente_id)
    end
end

app/helpers/mediciones_helper.rb
module MedicionesHelper
end

app/views/mediciones/_form.html.erb
<article id="datos-mediciones" class="container-fluid cuerpo">
	<section class="titulo" class="row">
		<div class="col-xs-12 text-center sub-titulo">
			<h2 class="titulosMovil"> 2 <span class="rojo">/</span> INTRODUCCIÓN DE DATOS</h2>
		</div>
	</section>

	<section class="row cuadro-foto">
		<div class="col-sm-offset-2 col-sm-6 col-xs-12">
			<%= form_for [@paciente, @medicione] do |f| %>
			<% if @medicione.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@medicione.errors.count, "error") %> prohibited this medicione from being saved:</h2>

				<ul>
					<% @medicione.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<div class="form-group paddingtop paddingbottom">
				<label class="control-label col-xs-12">COMISURA LABIAL / BORDE EXTERIOR DEL OJO:</label>
				<div class="col-sm-6 col-xs-12">
					<%= f.text_field :ojo_comisura_derecho, class: 'form-control', placeholder: 'Lado DERECHO'%>
				</div>
				<div class="col-sm-6 col-xs-12">
					<%= f.text_field :ojo_comisura_izquierdo, class: 'form-control', placeholder: 'Lado IZQUIERDO'%>
				</div>
			</div>

			<div class="form-group paddingtop paddingbottom">
				<div class="col-sm-6 col-xs-12">
				  <label class="control-label col-xs-12">ALTURA DEL LABIO SUPERIOR:</label>
					<%= f.text_field :altura_labio_superior, class: 'form-control', placeholder: 'Altura Labio Superior' %>
				</div>
				<div class="col-sm-6 col-xs-12">
				  <label class="control-label col-xs-12">ALTURA DEL LABIO INFERIOR:</label>
					<%= f.text_field :altura_labio_inferior, class: 'form-control', placeholder: 'Altura Labio Inferior' %>
				</div>
			</div>

      <div class="form-group paddingtop paddingbottom">
	      <div class="col-sm-6 col-xs-12">
	        <label class="control-label col-xs-12">FILTRO</label>
		      <%= f.text_field :leporino, class: 'form-control', placeholder: 'FILTRO'%>
	      </div>
	      <div class="col-sm-6 col-xs-12">
	        <label class="control-label col-xs-12">TRICHION / GNATIO:</label>
		      <%= f.text_field :trichion_menton, class: 'form-control', placeholder: 'TRICHION / GNATIO:'%>
	      </div>
      </div>
      <div class="form-group paddingtop paddingbottom">
        <div class="col-sm-12 col-xs-12">
          <label class="control-label col-xs-12">DISTANCIA INTERCISIVA MAXIMA</label>
          <%= f.text_field :distancia_intercisiva_maxima, class: 'form-control', placeholder: 'DISTANCIA INTERCISIVA MAXIMA' %>
        </div>
      </div>

      <div class="form-group paddingtop paddingbottom">
	      <label class="control-label col-xs-12">TERCIOS</label>
	      <div class="col-sm-4 col-xs-12">
		      <%= f.text_field :tercio_superior, class: 'form-control', placeholder: 'SUPERIOR (Trichion a Glabela)'%>
	      </div>
	      <div class="col-sm-4 col-xs-12">
		      <%= f.text_field :tercio_medio, class: 'form-control', placeholder: 'MEDIO (Glabela a Subnasal)'%>
	      </div>
	      <div class="col-sm-4 col-xs-12">
		      <%= f.text_field :tercio_inferior, class: 'form-control', placeholder: 'INFERIOR (Subnasal a Gnation)'%>
	      </div>
      </div>

      <div class="form-group paddingtop paddingbottom">
	      <label class="control-label col-xs-12">TERCIOS del 1/3 INFERIOR</label>
	      <div class="col-sm-4 col-xs-12">
		      <%= f.text_field :tercio_inferior_superior, class: 'form-control', placeholder: 'SUPERIOR (Subnasal a Estomio)'%>
	      </div>
	      <div class="col-sm-4 col-xs-12">
		      <%= f.text_field :tercio_inferior_medio, class: 'form-control', placeholder: 'MEDIO (Estomio a Supramentoniano)'%>
	      </div>
	      <div class="col-sm-4 col-xs-12">
		      <%= f.text_field :tercio_inferior_inferior, class: 'form-control', placeholder: 'INFERIOR (Supramentoniano a Gnatio)'%>
	      </div>
      </div>

      <div class="field">
	      <%= f.label :paciente_id, hidden: '' %>
	      <%= f.text_field :paciente_id, hidden: '', value: @paciente.id %>
      </div>
    </div>
</div>
</div>

<div class="col-sm-4">
  <%= image_tag 'malla-01.jpg', alt:'', width:'80%', style: 'margin:auto' %>
  <%= button_tag 'Subir fotografia', class: 'btn btn-default' %>
</div>
</section>

<section class="navegacion row paddingtop text-center">
	<div class="col-sm-offset-1 col-sm-5 col-xs-offset-2 col-xs-4">
		<span class="glyphicon glyphicon-circle-arrow-left btn-pasos new-medicion"></span>
	</div>
	<div class="col-sm-5 col-xs-4">
		<span class="glyphicon glyphicon-circle-arrow-right btn-pasos new-medicion"></span>
	</div>
</section>
</article>
<% end %>

app/views/mediciones/edit.html.erb
<h1>Editing Medicione</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicione %> |
<%= link_to 'Back', mediciones_path %>

app/views/mediciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mediciones</h1>

<table>
  <thead>
    <tr>
      <th>Ojo derecho</th>
      <th>Ojo izquierdo</th>
      <th>Oreja izquierda</th>
      <th>Oreja derecha</th>
      <th>Cupido izquierdo</th>
      <th>Cupido derecho</th>
      <th>Leporino</th>
      <th>Paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mediciones.each do |medicione| %>
      <tr>
        <td><%= medicione.ojo_comisura_derecho %></td>
        <td><%= medicione.ojo_comisura_izquierdo %></td>
        <td><%= medicione.leporino %></td>
        <td><%= medicione.trichion_menton %></td>
        <td><%= medicione.tercio_superior %></td>
        <td><%= medicione.tercio_medio %></td>
        <td><%= medicione.tercio_inferior %></td>
        <td><%= medicione.tercio_inferior_superior %></td>
        <td><%= medicione.tercio_inferior_medio %></td>
        <td><%= medicione.tercio_inferior_inferior %></td>
        <td><%= link_to 'Show', medicione_path(params[:paciente_id], medicione) %></td>
        <td><%= link_to 'Edit', edit_medicione_path(params[:paciente_id], medicione) %></td>
        <td><%= link_to 'Destroy', medicione_path(params[:paciente_id], medicione), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicione', new_paciente_medicione_path %>

app/views/mediciones/new.html.erb
<%= render 'form' %>

app/views/mediciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ojo derecho:</strong>
  <%= @medicione.ojo_comisura_derecho %>
</p>

<p>
  <strong>Ojo izquierdo:</strong>
  <%= @medicione.ojo_comisura_izquierdo %>
</p>

<p>
  <strong>Leporino:</strong>
  <%= @medicione.leporino %>
</p>
<%= @medicione.trichion_menton %>
<%= @medicione.tercio_superior %>
<%= @medicione.tercio_medio %>
<%= @medicione.tercio_inferior %>
<%= @medicione.tercio_inferior_superior %>
<%= @medicione.tercio_inferior_medio %>
<%= @medicione.tercio_inferior_inferior %>
<p>
  <strong>Paciente:</strong>
  <%= @medicione.paciente.nombre %>
</p>

<%= link_to 'Edit', edit_medicione_path(params[:paciente_id], @medicione) %> |
<%= link_to 'Back', paciente_mediciones_path(params[:paciente_id]) %>