config/routes.rb
Rails.application.routes.draw do

  get 'imagenes/frontal'
  get 'imagenes/perfil'
  resources :pacientes, shallow: true do
    resources :mediciones
  end

  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  get 'estatico/perfil'
  get 'estatico/resultados'
  get 'estatico/grafica'
  get 'estatico/tulogopeda'

  root to: "estatico#inicio"

end

app/views/layouts/_footer.html.erb
<footer>
  <section id="derechos" class="paddingbottom">
    <div class="col-xs-12 text-center">
      <p>2106 &copy; Todos los derechos reservados</p>
    </div>
  </section>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav id="MenuPrincipal" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- El logotipo y el icono que despliega el menú se agrupan
    para mostrarlos mejor en los dispositivos móviles -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
      data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"></a>
    </div>

    <!-- Agrupar los enlaces de navegación, los formularios y cualquier
    otro elemento que se pueda ocultar al minimizar la barra -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/">INICIO /</a></li>
        <li><%= link_to "TU LOGOPEDA /", estatico_tulogopeda_path %></li>
        <li><%= link_to "TU APLICACION /", pacientes_path %></li>
        <li>
            <% if user_signed_in? %>
                <%= link_to "SALIR /", destroy_user_session_path, method: :delete  %>
            <% else %>
                <%= link_to "REGÍSTRATE", new_user_registration_path %>
                <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logopedia</title>
  <meta charset = "UTF-8" />
  <meta name="viewport" content="width=device-width; initial-scale=1.0">
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <meta name="author" content="" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="overflow-y: scroll; overflow-x: auto;">
  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <section class="cuerpoGenerico">
    <%= yield %>
  </section>

  <%= render 'layouts/footer' %>
</body>
</html>